# Generated by Django 2.1.5 on 2020-06-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_auto_20200629_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_imgs', models.ImageField(default='default.png', upload_to='post_photo/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Upload.Uploads')),
            ],
        ),
    ]
