# Generated by Django 2.1.5 on 2020-06-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0003_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='post_img',
        ),
    ]
