# Generated by Django 2.1.5 on 2020-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0005_auto_20200703_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='post_imgs',
            field=models.ImageField(default='default.png', upload_to='post_photo/'),
        ),
    ]
