# Generated by Django 3.1rc1 on 2020-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0008_auto_20200704_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='code',
            field=models.TextField(default=True),
        ),
    ]
